name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # 升级到最新版

      # 设置Ruby环境（核心修改）
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'       # 明确指定3.0版本
          bundler-cache: true       # 自动处理bundle缓存
          cache-version: 1          # 缓存版本标识

      # 安装系统依赖（仅必要组件）
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zlib1g-dev build-essential

      # 安装项目依赖
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # 使用现代部署方式
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          keep_files: false
