name: GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      # 设置Ruby环境
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # 升级到Ruby 3.1
          bundler-cache: true

      # 安装编译依赖
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential patch

      # 安装项目依赖
      - name: Bundle install
        run: |
          bundle config set force_ruby_platform true
          bundle install --jobs 4 --retry 3

      # 更新 rake 版本
      - name: Update rake
        run: bundle update rake

      # 构建网站
      - name: Build site
        run: bundle exec jekyll build

      # 部署到GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
